# cargo-deny configuration: block risky licenses and known-bad deps

[advisories]
unmaintained = "workspace"

# Yanked versions can be "allow" | "warn" | "deny"
yanked = "warn"

# Put specific advisories or yanked versions here to silence them, if needed.
# Examples:
# ignore = [
#   "RUSTSEC-20xx-xxxx",
#   { id = "RUSTSEC-20xx-xxxx", reason = "why this doesn't affect us" },
#   "some-crate@1.2.3",
# ]
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"

[sources]
unknown-registry = "deny"
unknown-git      = "deny"
allow-git        = []
