# cargo-deny configuration: block risky licenses and known-bad deps

[advisories]
# Scope for unmaintained advisories: "all" | "workspace" | "transitive" | "none"
unmaintained = "workspace"
# Yanked versions: "allow" | "warn" | "deny"
yanked = "warn"
# Silence specific advisories or yanked versions here if needed.
ignore = []

[licenses]
# As of 0.18.4+, licenses are denied unless explicitly allowed; "default" key was removed.
# List the SPDX identifiers you allow:
allow = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
confidence-threshold = 0.8
# Optional: warn if you list a license in `allow` that isn’t used.
unused-allowed-license = "warn"

[licenses.private]
ignore = true

[bans]
# Lint on duplicate versions across the graph
multiple-versions = "warn"

[sources]
# Only allow crates.io (by default) and no unknown git sources
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
