max_width = 100
use_small_heuristics = "Max"
reorder_imports = true

group_imports = "StdExternalCrate"

# format_code_in_doc_comments = true
# normalize_doc_attributes = true
# wrap_comments = true
# imports_granularity = "Crate"
# unstable_features = true
