edition = "2024"
max_width = 100
use_small_heuristics = "Max"
format_code_in_doc_comments = true
normalize_doc_attributes = true
imports_granularity = "Crate"
reorder_imports = true
wrap_comments = true