[package]
name = "symbol-coordinator-demo"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR MIT"

[dependencies]
order-router = { path = "../../engine/order-router" }
symbol-coordinator = { path = "../../engine/symbol-coordinator" }
whistle = { path = "../../engine/whistle" }
